language: php

php:
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - vendor
    - ~/.composer/cache
    - ~/cphalcon

before_install:
  - composer install --prefer-source --no-interaction --ignore-platform-reqs

script:
  - vendor/bin/phpunit tests/

notifications:
email: false